### ISSUE TITLE
Source request

### ISSUE THREAD

**Issue by ProgrammerDan** [Scuwr/Snitch-Visualizer#1]
Scuwr; thanks for this mod, it's immensely helpful. There are a few tweaks I'd love to be able to make to it, but given the source is closed and I'm too lazy to decompile, can't. Would you consider posting the source with an appropriate license? Thanks so much, your contribution with this mod is greatly appreciated.

**Comment by Scuwr** [comment]
I'd love to let you have the source code! I meant to post it, but I never got around to commenting it, which is also why it wasn't officially published as a mod for civcraft.. I never got around to it because being a double major at the Air Force Academy makes finding free time very difficult, another reason I've stopped playing on civcraft unfortunately.

I start Spring Break this weekend, so If you are okay with waiting a little bit, I'd still like to comment my source code so that it is easy to follow. Would this be alright?

Also, if you'd like to send me a reminder message on Saturday, that'd be great! :+1:

**Comment by ProgrammerDan** [comment]
Hey, I totally understand. Gotta be real though, I have a pile of projects I haven't posted because they aren't properly commented; and at this point probably won't get to it :D. So, I understand, and am definitely willing to wait a little bit. I'll shoot you a reminder on Saturday.

Don't kill yourself with the commenting though, even just class level javadoc will at least put you on par with the rest of the Civcraft server mods, hehe.

**Comment by Scuwr** [comment]
Okay, I've posted just the uncommented source code. I plan to work on it later today.

Also, I didn't post the full workspace folder because I don't know what licensing permissions are required for me to post the file from the Forge SDK. If you have any insight on what I need to do, or if I can post it as is, let me know and I'll take the appropriate so that you can easily pull the project and import it into Eclipse.

**Comment by ProgrammerDan** [comment]
If it's a Forge source or lib, you'll have to check their license -- I'm not up on them. If the project isn't configured/compiled using Maven or an equivalent dependency manager, it'd probably suffice at this point to post in the README the libraries you depend on to compile and run, if the broader workspace question goes unanswered.

**Comment by Scuwr** [comment]
Alright, everything should be done! Let me know if you see anything that I commented poorly and needs more explanation :+1:

**Comment by ProgrammerDan** [comment]
This is great. I was under the weather all weekend, and have only glanced at the code in a cursory manner, but this is great. Thanks so much for publishing the source! I'll open a new issue if for some reason anything is unclear.
